# Generated by Django 5.2 on 2025-04-24 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('negado', 'Negado'), ('devolucion', 'Devolución')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_moneda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrFactura', models.CharField(max_length=50)),
                ('monto', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('tasa', models.CharField(max_length=5)),
                ('idDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facturacion.departamentos')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clientes', to='facturacion.cliente')),
                ('id_estatus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facturacion.estatus')),
            ],
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPago', models.CharField(max_length=50)),
                ('monedaId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facturacion.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facturacion.factura')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facturacion.moneda')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(default='admin', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
