# Generated by Django 5.2 on 2025-04-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(default=str, max_length=30),
            preserve_default=False,
        ),
    ]
