# Generated by Django 5.2 on 2025-05-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_pago_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.departamentos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tienda', 'Usuario de Tienda')], default='tienda', max_length=20),
        ),
    ]
