# Generated by Django 5.2 on 2025-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_profile_departamento_alter_profile_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='monto',
            new_name='montoBS',
        ),
        migrations.AddField(
            model_name='pago',
            name='montoUSD',
            field=models.FloatField(default=float),
            preserve_default=False,
        ),
    ]
